name: Build and Publish storybook to GitHub Pages

on:
  push:
    paths: ["src/main/webpack/**"]
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
      with:
        path: /storybook-static
        build_command: npm run build-storybook